[package]
name = "dylibtest"
version = "0.1.0"
authors = ["Thom Chiovoloni <chiovolonit@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "dylibtest"
crate_type = ["cdylib"]
path = "lib.rs"

[dependencies]
startup = { path = "../.." }
